version: '3'
services:
  web:
    image: spotify-docker-app
    depends_on:
      - redis
    ports: 
      - "3000:3000"
    networks:
      - monreseau
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - monreseau
networks:
  monreseau:
    
    